@echo off
echo Baixando Pagina Inicial...
curl -L -o index.html "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sXzQ0OTAyNTczODFiZjQ5MDY4Mzc1MjdiOGNmNTllNGFkEgsSBxCZp8TnsQwYAZIBIwoKcHJvamVjdF9pZBIVQhMzMDE1MTM1NDAxODQxMjE3MjI0&filename=&opi=89354086"
echo Baixando Detalhes do Produto...
curl -L -o produto.html "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sXzM4MDNjZDY2NzRjODQ2YmE5ZWM1ODk3Y2E1Yjc5ZDU1EgsSBxCZp8TnsQwYAZIBIwoKcHJvamVjdF9pZBIVQhMzMDE1MTM1NDAxODQxMjE3MjI0&filename=&opi=89354086"
echo Baixando Pagina de Contato...
curl -L -o contato.html "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sXzBhOTNiNjQ1Y2Q5ZDQzNzA4MTlkYWI1ZGQ3NTU2OGFlEgsSBxCZp8TnsQwYAZIBIwoKcHJvamVjdF9pZBIVQhMzMDE1MTM1NDAxODQxMjE3MjI0&filename=&opi=89354086"
echo Baixando Dashboard de Pedidos...
curl -L -o dashboard.html "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sXzcwM2ExZTI3MzBlZTRjMTViZmQ4M2EzYjdlOTlkNGU3EgsSBxCZp8TnsQwYAZIBIwoKcHJvamVjdF9pZBIVQhMzMDE1MTM1NDAxODQxMjE3MjI0&filename=&opi=89354086"
echo Todas as paginas do Stitch foram baixadas com sucesso!
pause
