@echo off
echo Adicionando arquivos ao Git...
git add .
echo Comitando alteracoes...
git commit -m "Upload do projeto para o repositorio"
echo Configurando remote origin...
git remote add origin https://github.com/Henrique-magdalena/Site-Teste.git
echo Enviando para o GitHub...
git push Site-Teste master
git push origin master
pause
